# Generated by Django 5.1.6 on 2025-03-21 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_book_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='published_date',
        ),
    ]
