# Generated by Django 5.1.6 on 2025-03-21 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_book_published_date'),
    ]

    operations = [
    ]
